/**for mc74 */
#include "drv_time.h"
#include "drv_uart.h"
#include "drv_io.h"
#include "main.h"
#include "drv_time.h"

/** set all of leds to off  */
void LEDInit()
{
    /**change a led state  */
    HAL_GPIO_WritePin(MCU_1_POINT_LED_D_GPIO_Port, MCU_1_POINT_LED_D_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(MCU_MAIN_EN_POINT_LED_GPIO_Port, MCU_MAIN_EN_POINT_LED_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(MCU_TB_EN_POINT_LED_GPIO_Port, MCU_TB_EN_POINT_LED_Pin, GPIO_PIN_RESET);
    /**enable le */
    HAL_GPIO_WritePin(MCU_DIC1_EN_POINT_LED_GPIO_Port, MCU_DIC1_EN_POINT_LED_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(MCU_DIC2_EN_POINT_LED_GPIO_Port, MCU_DIC2_EN_POINT_LED_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(MCU_DOC1_EN_POINT_LED_GPIO_Port, MCU_DOC1_EN_POINT_LED_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(MCU_DOC2_EN_POINT_LED_GPIO_Port, MCU_DOC2_EN_POINT_LED_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(MCU_AIC_EN_POINT_LED_GPIO_Port, MCU_AIC_EN_POINT_LED_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(MCU_HIOC1_EN_POINT_LED_GPIO_Port, MCU_HIOC1_EN_POINT_LED_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(MCU_HIOC2_EN_POINT_LED_GPIO_Port, MCU_HIOC2_EN_POINT_LED_Pin, GPIO_PIN_RESET);
    /**let all led off */
    for (uint8_t pins = 8; pins--;)
    {
        HAL_GPIO_WritePin(MCU_1_POINT_LED_A0_GPIO_Port, MCU_1_POINT_LED_A0_Pin, pins & 0x1UL << 0 ? GPIO_PIN_SET : GPIO_PIN_RESET);
        HAL_GPIO_WritePin(MCU_1_POINT_LED_A1_GPIO_Port, MCU_1_POINT_LED_A1_Pin, pins & 0x1UL << 1 ? GPIO_PIN_SET : GPIO_PIN_RESET);
        HAL_GPIO_WritePin(MCU_1_POINT_LED_A2_GPIO_Port, MCU_1_POINT_LED_A2_Pin, pins & 0x1UL << 2 ? GPIO_PIN_SET : GPIO_PIN_RESET);
        DelayUs(2);
    }
    /**disable le */
    HAL_GPIO_WritePin(MCU_MAIN_EN_POINT_LED_GPIO_Port, MCU_MAIN_EN_POINT_LED_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_TB_EN_POINT_LED_GPIO_Port, MCU_TB_EN_POINT_LED_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_DIC1_EN_POINT_LED_GPIO_Port, MCU_DIC1_EN_POINT_LED_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_DIC2_EN_POINT_LED_GPIO_Port, MCU_DIC2_EN_POINT_LED_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_DOC1_EN_POINT_LED_GPIO_Port, MCU_DOC1_EN_POINT_LED_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_DOC2_EN_POINT_LED_GPIO_Port, MCU_DOC2_EN_POINT_LED_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_AIC_EN_POINT_LED_GPIO_Port, MCU_AIC_EN_POINT_LED_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_HIOC1_EN_POINT_LED_GPIO_Port, MCU_HIOC1_EN_POINT_LED_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_HIOC2_EN_POINT_LED_GPIO_Port, MCU_HIOC2_EN_POINT_LED_Pin, GPIO_PIN_SET);
    /**change state to high */
    HAL_GPIO_WritePin(MCU_1_POINT_LED_D_GPIO_Port, MCU_1_POINT_LED_D_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_1_POINT_LED_A0_GPIO_Port, MCU_1_POINT_LED_A0_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_1_POINT_LED_A1_GPIO_Port, MCU_1_POINT_LED_A1_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_1_POINT_LED_A2_GPIO_Port, MCU_1_POINT_LED_A2_Pin, GPIO_PIN_SET);
    DelayUs(2);
}

/**write a led
 * ledId
 * ledState : 0 1
 */
void WriteLED(uint32_t ledId, uint8_t ledState)
{
    /**change a led state  */
    HAL_GPIO_WritePin(MCU_1_POINT_LED_D_GPIO_Port, MCU_1_POINT_LED_D_Pin, ledState ? GPIO_PIN_SET : GPIO_PIN_RESET);
    HAL_GPIO_WritePin(MCU_1_POINT_LED_A0_GPIO_Port, MCU_1_POINT_LED_A0_Pin, ledId & 0x1UL << 0 ? GPIO_PIN_SET : GPIO_PIN_RESET);
    HAL_GPIO_WritePin(MCU_1_POINT_LED_A1_GPIO_Port, MCU_1_POINT_LED_A1_Pin, ledId & 0x1UL << 1 ? GPIO_PIN_SET : GPIO_PIN_RESET);
    HAL_GPIO_WritePin(MCU_1_POINT_LED_A2_GPIO_Port, MCU_1_POINT_LED_A2_Pin, ledId & 0x1UL << 2 ? GPIO_PIN_SET : GPIO_PIN_RESET);
    /**enable le */
    HAL_GPIO_WritePin(MCU_MAIN_EN_POINT_LED_GPIO_Port, MCU_MAIN_EN_POINT_LED_Pin, ledId & 0x1UL << 3 ?    GPIO_PIN_RESET : GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_TB_EN_POINT_LED_GPIO_Port, MCU_TB_EN_POINT_LED_Pin, ledId & 0x1UL << 4 ?        GPIO_PIN_RESET : GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_DIC1_EN_POINT_LED_GPIO_Port, MCU_DIC1_EN_POINT_LED_Pin, ledId & 0x1UL << 5 ?    GPIO_PIN_RESET : GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_DIC2_EN_POINT_LED_GPIO_Port, MCU_DIC2_EN_POINT_LED_Pin, ledId & 0x1UL << 6 ?    GPIO_PIN_RESET : GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_DOC1_EN_POINT_LED_GPIO_Port, MCU_DOC1_EN_POINT_LED_Pin, ledId & 0x1UL << 7 ?    GPIO_PIN_RESET : GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_DOC2_EN_POINT_LED_GPIO_Port, MCU_DOC2_EN_POINT_LED_Pin, ledId & 0x1UL << 8 ?    GPIO_PIN_RESET : GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_AIC_EN_POINT_LED_GPIO_Port, MCU_AIC_EN_POINT_LED_Pin, ledId & 0x1UL << 9 ?      GPIO_PIN_RESET : GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_HIOC1_EN_POINT_LED_GPIO_Port, MCU_HIOC1_EN_POINT_LED_Pin, ledId & 0x1UL << 10 ? GPIO_PIN_RESET : GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_HIOC2_EN_POINT_LED_GPIO_Port, MCU_HIOC2_EN_POINT_LED_Pin, ledId & 0x1UL << 11 ? GPIO_PIN_RESET : GPIO_PIN_SET);
    DelayUs(2);
    /**set high all of pins */
    /**disable le */
    HAL_GPIO_WritePin(MCU_MAIN_EN_POINT_LED_GPIO_Port, MCU_MAIN_EN_POINT_LED_Pin,   GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_TB_EN_POINT_LED_GPIO_Port, MCU_TB_EN_POINT_LED_Pin,       GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_DIC1_EN_POINT_LED_GPIO_Port, MCU_DIC1_EN_POINT_LED_Pin,   GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_DIC2_EN_POINT_LED_GPIO_Port, MCU_DIC2_EN_POINT_LED_Pin,   GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_DOC1_EN_POINT_LED_GPIO_Port, MCU_DOC1_EN_POINT_LED_Pin,   GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_DOC2_EN_POINT_LED_GPIO_Port, MCU_DOC2_EN_POINT_LED_Pin,   GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_AIC_EN_POINT_LED_GPIO_Port, MCU_AIC_EN_POINT_LED_Pin,     GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_HIOC1_EN_POINT_LED_GPIO_Port, MCU_HIOC1_EN_POINT_LED_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_HIOC2_EN_POINT_LED_GPIO_Port, MCU_HIOC2_EN_POINT_LED_Pin, GPIO_PIN_SET);
    /**change state to high */
    HAL_GPIO_WritePin(MCU_1_POINT_LED_D_GPIO_Port, MCU_1_POINT_LED_D_Pin,           GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_1_POINT_LED_A0_GPIO_Port, MCU_1_POINT_LED_A0_Pin,         GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_1_POINT_LED_A1_GPIO_Port, MCU_1_POINT_LED_A1_Pin,         GPIO_PIN_SET);
    HAL_GPIO_WritePin(MCU_1_POINT_LED_A2_GPIO_Port, MCU_1_POINT_LED_A2_Pin,         GPIO_PIN_SET);
    DelayUs(2);
}
